I18n.ca =
  menu:
    schema: "Esquema"
    new: "Nou ..."
    load: "Carrega ..."
    save: "Desa"
    save_as: "Anomena i desa ..."
    templates: "Plantilles ..."
    properties: "Propietats ..."
    share: "Compartir ..."
    import: "Importa ..."
    edit: "Edita"
    undo: "Desfer"
    redo: "Refer"
    insert: "Insereix"
    table: "Taula"
    note: "Nota"
    view: "Veure"
    show_minimap: "Mostra minimapa"
    hide_minimap: "Amaga minimapa"
    show_sidebar: "Mostra Barra Lateral"
    hide_sidebar: "Amaga Barra Lateral"
    show_grid: "Show Grid"
    hide_grid: "Hide Grid"
    sort_items: "Ordenar Articles"
    linetype: "Tipus de Línia"
    bezier: "Corba"
    cornered: "Recta"
    options: "Opcions ..."
    export: "Exporta"
    sql: "a Sql ..."
    image: "a Imatge ..."
    help: "Ajuda"
    index: "Índex"
    changes: "Canvis"
    shortcuts: "Dreceres de Teclat"
    feedback: "Retroalimentació"
    about: "Quant a"
    guest: "Convidat"
    login: "Iniciar Sessió"
    logout: "Tancar Sessió"
    settings: "Preferències"
  panel:
    history: "Historial"
    last_versions_label: "Ultimes 10 versions d'aquest esquema:"
    properties: "Propietats"
    properties_schema_name: "Nom de l'esquema:"
    properties_database: "Base de dades:"
    comments: "Comentaris"
    comment_placeholder: "Introdueix el teu comentari aquí"
    send: "Enviar"
  dialog:
    new_schema: "Nou Esquema"
    new_schema_title: "Títol"
    new_schema_database: "Base de dades"
    new_schema_type_info: """Seleccionar el tipus de base de dades "genèric" et permetrà generar les sentències SQL per a totes les bases de dades, però només podràs tenir accés als tipus de dades genèrics."""
    new_schema_create_new: "Crear nou esquema"
    load_schema: "Carregar esquema"
    load_schema_your_schemas: "Els teus esquemes:"
    load_schema_schema_name: "Nom de l'esquema"
    load_schema_database: "Base de dades"
    load_schema_last_save: "Últim desat"
    load_schema_shared_with_you: "Esquemes compartits amb tu:"
    load_schema_owner: "Propietari"
    load_schema_no_schemas: "No has desat cap esquema"
    load_schema_no_shared_schemas: "No s'està compartint cap esquema amb tu"
    saveas: "Anomena i desa ..."
    saveas_title: "Títol"
    saveas_button: "Desa"
    templates: "Plantilles"
    templates_schema_name: "Nom de l'esquema"
    templates_database: "Base de dades"
    templates_description: "Descripció"
    properties: "Propietats de l'Esquema"
    properties_title: "Títol"
    properties_publish: "Publicar com a plantilla"
    properties_template_info: "(Les plantilles són visibles per a tots els usuaris)"
    properties_delete_schema: "Esborrar Esquema"
    properties_delete_alert: "(S'esborrarà de manera permanent aquest esquema i tots els seus comentaris associats)"
    properties_save: "Desar Canvis"
    share: "Compartir"
    share_info: "Pots compartir el teu esquema fins a 5 usuaris"
    share_email: "Correu electrònic"
    share_access: "Accés"
    share_read_only: "Només lectura"
    share_read_write: "Lectura i escriptura"
    share_send_email: "Enviar invitació per correu electrònic"
    share_invite_button: "Convida"
    share_collaborators: "Col·laboradors:"
    import: "Importar Sql"
    login_email: "Correu electrònic"
    login_password: "Contrasenya"
    login_button: "Iniciar Sessió"
    login_forgot_password: "He oblidat la contrasenya"
    options: "Opcions"
    options_line_colors: "Colors de línia"
    options_invert_line_direction: "Invertir direcció de la línia"
    options_show_fk_icon: "Mostra la icona de la clau forana"
    options_show_not_null_icon: "Mostra la icona del Valor no Nul"
    options_show_default_values: "Mostra Valors Per Defecte"
    options_language: "Llenguatge"
    options_save_changes: "Desa els canvis"
    export_sql: "Exporta SQL"
    export_sql_generate: "Generar SQL"
    export_sql_download: "Descarrega arxiu SQL"
    export_image: "Exporta Imatge"
    export_image_zoomin: "Apropar"
    export_image_zoomout: "Allunyar"
    export_image_reset: "Reiniciar"
    export_image_open_in_new_tab: "Obrir la imatge en una pestanya nova"
    help: "Ajuda"
    shortcuts: "Dreceres de teclat"
    help_changelog: "Canvis"
    feedback: "Retroalimentació"
    feedback_type: "Tipus de retroalimentació"
    feedback_bug: "Informe d'errors"
    feedback_feature: "Sol·licitud de funció"
    feedback_help: "Ajuda"
    feedback_other: "Un altre"
    feedback_message: "Missatge"
    feedback_button: "Enviar retroalimentació"
    about: "Sobre dbdesigner.net"
    user_settings: "Preferències de l'Usuari"
    user_settings_username: "Nom de l'Usuari"
    user_settings_email: "Correu electrònic"
    user_settings_save: "Desa els Canvis"
    login: "Iniciar Sessió"
    close: "Tancar"
  designer:
    save_note_edit: "Desa"
    cancel_note_edit: "Cancel·la"
    delete_note: "Esborrar"
    table_save: "Desa"
    table_cancel: "Cancel·la"
    table_delete: "Esborra Taula"
    table_clone: "Clona Taula"
    table_add_field: "Afegeix Camp"
    field_name: "Nom"
    field_type: "Tipus"
    field_size: "Mida"
    field_default: "Per Defecte"
    field_allow_nulls: "Permetre valors nuls"
    field_primary_key: "Clau Primària"
    field_foreign_key: "Clau Forana"
    field_save: "Desa"
    field_update: "Actualitzar"
    field_cancel: "Cancel·la"
    field_delete: "Esborra Camp"
    field_delete_alert: "Esteu segur que voleu esborrar aquest camp?\n(mantingui pressionat shift per esborrar sense confirmació)"
    field_ref_table: "Taula de Referència"
    field_ref_field: "Camp de Referència"
  alerts:
    delete_schema: "Esteu segur que voleu esborrar aquest esquema?"
    server_error: "Hi ha hagut un error del servidor"
    schema_owner_error: "Només el propietari de l'esquema pot canviar la configuració de compartir"
    login_to_use_this_function: "Heu d'entrar per utilitzar aquesta funció"