I18n.de =
  menu:
    schema: "Schema"
    new: "Neu ..."
    load: "Laden ..."
    save: "Speichern"
    save_as: "Speichern unter ..."
    templates: "Vorlagen ..."
    properties: "Eigenschaften ..."
    share: "Teilen ..."
    import: "Importieren ..."
    edit: "Bearbeiten"
    undo: "Zurück"
    redo: "Wiederherstellen"
    insert: "Einfügen"
    table: "Tabelle"
    note: "Notiz"
    view: "Ansicht"
    show_minimap: "Minimap einblenden"
    hide_minimap: "Minimap ausblenden"
    show_sidebar: "Seitenleiste einblenden"
    hide_sidebar: "Seitenleiste ausblenden"
    show_grid: "Gitter einblenden"
    hide_grid: "Gitter einblenden"
    sort_items: "Items sortieren"
    linetype: "Linientyp"
    bezier: "gekurvt"
    cornered: "eckig"
    options: "Optionen ..."
    export: "Exportieren"
    sql: "SQL ..."
    image: "Bild ..."
    help: "Hilfe"
    index: "Index"
    changes: "Änderungen"
    shortcuts: "Tastaturkürzel"
    feedback: "Feedback"
    about: "Über"
    guest: "Gast"
    login: "Login"
    logout: "Logout"
    settings: "Einstellungen"
  panel:
    history: "Verlauf"
    last_versions_label: "Die letzten 10 Versionen dieses Schemas:"
    properties: "Eigenschaften"
    properties_schema_name: "Name des Schemas:"
    properties_database: "Datenbank:"
    comments: "Kommentare"
    comment_placeholder: "Kommentar hier einfügen"
    send: "Senden"
  dialog:
    new_schema: "Neues Schema"
    new_schema_title: "Titel"
    new_schema_database: "Datenbank"
    new_schema_type_info: """Mit dem Datenbank Typ "generic" können SQL-Befehle für alle Datenbanken erstellt werden. Allerdings können damit nur die allgemeinen Datentypen verwendet werden."""
    new_schema_create_new: "Neues Schema erstellen"
    load_schema: "Schema laden"
    load_schema_your_schemas: "Vorhandene Schemata:"
    load_schema_schema_name: "Name"
    load_schema_database: "Datenbank"
    load_schema_last_save: "Letztes Speicherdatum"
    load_schema_shared_with_you: "Schemata von anderen:"
    load_schema_owner: "Besitzer"
    load_schema_no_schemas: "Keine Schemata vorhanden"
    load_schema_no_shared_schemas: "Keine Schemata vorhanden"
    saveas: "Speichern unter"
    saveas_title: "Titel"
    saveas_button: "Speichern unter"
    templates: "Vorlagen"
    templates_schema_name: "Name"
    templates_database: "Datenbank"
    templates_description: "Beschreibung"
    properties: "Eigenschaften"
    properties_title: "Titel"
    properties_publish: "Als Vorlage veröffentlichen"
    properties_template_info: "(Vorlagen sind für alle Benutzer sichtbar)"
    properties_delete_schema: "Schema löschen"
    properties_delete_alert: "(Das Schema und alle damit verbundenen Kommentare werden für immer gelöscht)"
    properties_save: "Speichern"
    share: "Teilen"
    share_info: "Schemata können mit bis zu 5 anderen Nutzern geteilt werden"
    share_email: "E-mail"
    share_access: "Berechtigung"
    share_read_only: "Nur Lesen"
    share_read_write: "Lesen und Schreiben"
    share_send_email: "Einladungsmail verschicken"
    share_invite_button: "Einladen"
    share_collaborators: "Mitarbeiter:"
    import: "SQL importieren"
    login_email: "E-mail"
    login_password: "Passwort"
    login_button: "Login"
    login_forgot_password: "Passwort vergessen"
    options: "Weitere Optionen"
    options_line_colors: "Linienfarbe"
    options_invert_line_direction: "Linienausrichtung umdrehen"
    options_show_fk_icon: "Zeige Icon für fremde Schlüssel"
    options_show_not_null_icon: "Zeige Icon für erlaubte Nullwerte"
    options_show_default_values: "Zeige Standardwerte"
    options_language: "Sprache"
    options_save_changes: "Speichern"
    export_sql: "SQL exporieren"
    export_sql_generate: "SQL generieren"
    export_sql_download: "SQL Datei herunterladen"
    export_image: "Bild exportieren"
    export_image_zoomin: "Einzoomen"
    export_image_zoomout: "Auszoomen"
    export_image_reset: "Zurücksetzen"
    export_image_open_in_new_tab: "Bild in neuem Tab öffnen"
    help: "Hilfe"
    shortcuts: "Tastaturkürzel"
    help_changelog: "Veränderungen"
    feedback: "Feedback"
    feedback_type: "Art des Feedbacks"
    feedback_bug: "Fehler gefunden"
    feedback_feature: "Wunsch für eine Funktion"
    feedback_help: "Hilfe"
    feedback_other: "Sonstiges"
    feedback_message: "Nachricht"
    feedback_button: "Senden"
    about: "Über dbdesigner.net"
    user_settings: "Nutzereinstellungen"
    user_settings_username: "Benutzername"
    user_settings_email: "E-mail"
    user_settings_save: "Speichern"
    login: "Login"
    close: "Schließen"
    back: "Zurück"
  designer:
    save_note_edit: "Sichern"
    cancel_note_edit: "Abbrechen"
    delete_note: "Löschen"
    table_name: "Tabellenname"
    table_comment: "Tabellenkommentar"
    table_save: "Speichern"
    table_cancel: "Abbrechen"
    table_delete: "Tabelle löschen"
    table_clone: "Tabelle duplizieren"
    table_add_field: "Feld hinzufügen"
    field_name: "Name"
    field_type: "Typ"
    field_size: "Größe"
    field_default: "Standardwert"
    field_allow_nulls: "Nullwerte erlauben"
    field_primary_key: "Primärschlüssel"
    field_foreign_key: "Fremder Schlüssel"
    field_save: "Speichern"
    field_update: "Speichern"
    field_cancel: "Abbrechen"
    field_delete: "Feld löschen"
    field_delete_alert: "Sind Sie sicher, dass Sie dieses Feld löschen möchten?\n(Shifttaste gedrückt halten, um ohne Bestätigung zu löschen)"
    field_ref_table: "Tabelle"
    field_ref_field: "Feld"
  alerts:
    delete_schema: "Sind Sie sicher, dass sie dieses Schema löschen möchten?"
    server_error: "Ein Server-Fehler ist aufgetreten."
    schema_owner_error: "Nur der Besitzer eines Schemas kann die Teileneinstellungen ändern."
    login_to_use_this_function: "Bitte loggen Sie sich ein, um diese Funktion nutzen zu können."
