I18n.es =
  menu:
    schema: "Esquema"
    new: "Nuevo ..."
    load: "Cargar ..."
    save: "Guardar"
    save_as: "Guardar Como ..."
    templates: "Plantillas ..."
    properties: "Propiedades ..."
    share: "Compartir ..."
    import: "Importar ..."
    edit: "Editar"
    undo: "Deshacer"
    redo: "Rehacer"
    insert: "Insertar"
    table: "Tabla"
    note: "Nota"
    view: "Ver"
    show_minimap: "Mostrar Minimapa"
    hide_minimap: "Ocultar Minimapa"
    show_sidebar: "Mostrar Barra Lateral"
    hide_sidebar: "Ocultar Barra Lateral"
    sort_items: "Ordenar Artículos"
    linetype: "Tipo de Línea"
    bezier: "Curva"
    cornered: "Recta"
    options: "Opciones ..."
    export: "Exportar"
    sql: "Sql ..."
    image: "Imagen ..."
    help: "Ayuda"
    index: "Índice"
    changes: "Cambios"
    shortcuts: "Atajos de Teclado"
    feedback: "Retroalimentación"
    about: "Acerca de"
    guest: "Invitado"
    login: "Iniciar Sesión"
    logout: "Cerrar Sesión"
    settings: "Ajustes"
  panel:
    history: "Historial"
    last_versions_label: "Ultimas 10 versiones de este esquema:"
    properties: "Propiedades"
    properties_schema_name: "Nombre del esquema:"
    properties_database: "Base de datos:"
    comments: "Comentarios"
    comment_placeholder: "Ingresa tu comentario aquí"
    send: "Enviar"
  dialog:
    new_schema: "Nuevo Esquema"
    new_schema_title: "Titulo"
    new_schema_database: "Base de datos"
    new_schema_type_info: """Seleccionando el tipo de base de datos "genérico" le permitirá generar las sentencias SQL para todas las bases de datos; pero solo podrá tener acceso a los tipos de datos genéricos."""
    new_schema_create_new: "Crear nuevo esquema"
    load_schema: "Cargar esquema"
    load_schema_your_schemas: "Tus esquemas:"
    load_schema_schema_name: "Nombre del esquema"
    load_schema_database: "Base de datos"
    load_schema_last_save: "Ultimo guardado"
    load_schema_shared_with_you: "Esquemas compartidos contigo:"
    load_schema_owner: "Propietario"
    saveas: "Guardar Como"
    saveas_title: "Titulo"
    saveas_button: "Guardar Como"
    templates: "Plantillas"
    templates_schema_name: "Nombre del esquema"
    templates_database: "Base de datos"
    templates_description: "Descripción"
    properties: "Propiedades del Esquema"
    properties_title: "Titulo"
    properties_publish: "Publicar como plantilla"
    properties_template_info: "(Las plantillas son visibles para todos los usuarios)"
    properties_delete_schema: "Eliminar Esquema"
    properties_delete_alert: "(Eliminara de manera permanente este esquema y todos los comentarios asociados a el)"
    properties_save: "Guardar Cambios"
    share: "Compartir"
    share_info: "Puedes compartir tu esquema hasta con 5 usuarios"
    share_email: "Correo Electrónico"
    share_access: "Acceso"
    share_read_only: "Solo lectura"
    share_read_write: "Lectura y escritura"
    share_send_email: "Enviar invitación por correo electrónico"
    share_invite_button: "Invitar"
    share_collaborators: "Colaboradores:"
    import: "Importar Sql"
    login_email: "Correo Electrónico"
    login_password: "Contraseña"
    login_button: "Iniciar Sesión"
    login_forgot_password: "He olvidado mi contraseña"
    options: "Opciones"
    options_line_colors: "Colores de línea"
    options_invert_line_direction: "Invertir dirección de la línea"
    options_show_fk_icon: "Mostrar el icono de la llave foránea"
    options_show_not_null_icon: "Mostrar icono de Valor no Nulo"
    options_show_default_values: "Mostrar Valores Por Defecto"
    options_language: "Lenguaje"
    options_save_changes: "Guardar cambios"
    export_sql: "Exportar SQL"
    export_sql_generate: "Generar SQL"
    export_sql_download: "Descargar archivo SQL"
    export_image: "Exportar Imagen"
    export_image_zoomin: "Acercar"
    export_image_zoomout: "Alejar"
    export_image_reset: "Reiniciar"
    export_image_open_in_new_tab: "Abrir imagen en una pestaña nueva"
    help: "Ayuda"
    shortcuts: "Atajos de teclado"
    help_changelog: "Cambios"
    feedback: "Retroalimentación"
    feedback_type: "Tipo de retroalimentación"
    feedback_bug: "Reporte de errores"
    feedback_feature: "solicitud de función"
    feedback_help: "Ayuda"
    feedback_other: "Otro"
    feedback_message: "Mensaje"
    feedback_button: "Enviar retroalimentación"
    about: "Acerca de dbdesigner.net"
    user_settings: "Ajustes de Usuario"
    user_settings_username: "Nombre de Usuario"
    user_settings_email: "Correo Electrónico"
    user_settings_save: "Guardar Cambios"
    login: "Iniciar Sesión"
    close: "Cerrar"
  designer:
    save_note_edit: "Guardar"
    cancel_note_edit: "Cancelar"
    delete_note: "Eliminar"
    table_save: "Guardar"
    table_cancel: "Cancelar"
    table_delete: "Eliminar Tabla"
    table_add_field: "Añadir Campo"
    field_name: "Nombre"
    field_type: "Tipo"
    field_size: "Tamaño"
    field_default: "Por Defecto"
    field_allow_nulls: "Permitir valores nulos"
    field_primary_key: "Llave Primaria"
    field_foreign_key: "Llave Foránea"
    field_save: "Guardar"
    field_update: "Actualizar"
    field_cancel: "Cancelar"
    field_delete: "Eliminar Campo"
    field_delete_alert: "¿Esta seguro que desea eliminar este campo?\n(mantenga presionado shift para eliminar sin confirmación)"
    field_ref_table: "Tabla de Referencia"
    field_ref_field: "Campo de Referencia"
  alerts:
    delete_schema: "¿Esta seguro que desea eliminar este esquema?"
    server_error: "Ha ocurrido un error del servidor"
    schema_owner_error: "Solo el propietario del esquema puede cambiar los ajustes de compartir"
    login_to_use_this_function: "Debes iniciar sesión para utilizar esta función"
