I18n.fi =
  menu:
    schema: "Kaavio"
    new: "Uusi ..."
    load: "Avaa ..."
    save: "Tallenna"
    save_as: "Tallenna nimellä ..."
    templates: "Kaaviopohjat ..."
    properties: "Ominaisuudet ..."
    share: "Jaa ..."
    import: "Tuo ..."
    edit: "Muokkaa"
    undo: "Kumoa"
    redo: "Tee uudelleen"
    insert: "Luo"
    table: "Taulu"
    note: "Merkintä"
    view: "Näytä"
    show_minimap: "Näytä minikaavio"
    hide_minimap: "Piilota minikaavio"
    show_sidebar: "Näytä sivupalkki"
    hide_sidebar: "Piilota sivupalkki"
    show_grid: "Näytä ruudukko"
    hide_grid: "Piilota ruudukko"
    sort_items: "Järjestä automaattisesti"
    linetype: "Viivan tyyppi"
    bezier: "Kaareva"
    cornered: "Kulmikas"
    options: "Valinnat ..."
    export: "Vie"
    sql: "SQL ..."
    image: "Kuva ..."
    help: "Ohje"
    index: "Aiheet"
    changes: "Muutokset"
    shortcuts: "Näppäinoikotiet"
    feedback: "Palaute"
    about: "Tietoja"
    guest: "Vieras"
    login: "Kirjaudu"
    logout: "Kirjaudu ulos"
    settings: "Asetukset"
  panel:
    history: "Historia"
    last_versions_label: "Tämän kaavion 10 viimeisintä versiota:"
    properties: "Ominaisuudet"
    properties_schema_name: "Kaavion nimi:"
    properties_database: "Tietokanta:"
    comments: "Kommentit"
    comment_placeholder: "Syötä kommenttisi tähän"
    send: "Lähetä"
  dialog:
    new_schema: "Uusi kaavio"
    new_schema_title: "Nimi"
    new_schema_database: "Tietokanta"
    new_schema_type_info: """Valitsemalla "generic" tietokannan tyypiksi voit generoida SQL-skriptin mille tahansa tietokantatyypille, mutta kaaviossasi on käytössä ainoastaan geneeriset tietotyyppit."""
    new_schema_create_new: "Luo uusi kaavio"
    load_schema: "Avaa kaavio"
    load_schema_your_schemas: "Tallennetut kaaviot:"
    load_schema_schema_name: "Kaavion nimi"
    load_schema_database: "Tietokanta"
    load_schema_last_save: "Viimeksi tallennettu"
    load_schema_shared_with_you: "Kanssasi jaetut kaaviot:"
    load_schema_owner: "Omistaja"
    load_schema_no_schemas: "Et ole tallentanut yhtään kaaviota"
    load_schema_no_shared_schemas: "Yhtään kaaviota ei ole jaettu kanssasi"
    saveas: "Tallenna nimellä"
    saveas_title: "Nimi"
    saveas_button: "Tallenna"
    templates: "Kaaviopohjat"
    templates_schema_name: "Kaavion nimi"
    templates_database: "Tietokanta"
    templates_description: "Kuvaus"
    properties: "Kaavan ominaisuudet"
    properties_title: "Nimi"
    properties_publish: "Julkaise kaaviopohjana"
    properties_template_info: "(Kaaviopohjat näkyvät kaikille käyttäjille)"
    properties_delete_schema: "Poista kaavio"
    properties_delete_alert: "(Kaavio ja sen kommentit poistetaan pysyvästi)"
    properties_save: "Tallenna muutokset"
    share: "Jaa"
    share_info: "Voit jakaa kaaviosi korkeintaan viidelle käyttäjälle"
    share_email: "Sähköposti"
    share_access: "Pääsytaso"
    share_read_only: "Vain luku"
    share_read_write: "Luku ja kirjoitus"
    share_send_email: "Lähetä kutsu sähköpostilla"
    share_invite_button: "Kutsu"
    share_collaborators: "Jaettu seuraaville käyttäjille:"
    import: "Tuo SQL"
    login_email: "Sähköposti"
    login_password: "Salasana"
    login_button: "Kirjaudu sisään"
    login_forgot_password: "Olen unohtanut salasanani"
    options: "Valinnat"
    options_line_colors: "Viivan väri"
    options_invert_line_direction: "Vaihda nuolien suunta"
    options_show_fk_icon: "Näytä viiteavaimen ikoni"
    options_show_not_null_icon: "Näytä Not Null -ikoni"
    options_show_default_values: "Näytä oletusarvot"
    options_language: "Kieli"
    options_save_changes: "Tallenna muutokset"
    export_sql: "Vie SQL"
    export_sql_generate: "Generoi SQL"
    export_sql_download: "Lataa SQL-tiedosto"
    export_image: "Vie kuva"
    export_image_zoomin: "Lähennä"
    export_image_zoomout: "Loitonna"
    export_image_reset: "Palauta oletus"
    export_image_open_in_new_tab: "Avaa kuva uudessa välilehdessä"
    help: "Ohje"
    shortcuts: "Näppäinoikotiet"
    help_changelog: "Muutokset"
    feedback: "Palaute"
    feedback_type: "Palautteen tyyppi"
    feedback_bug: "Bugiraportti"
    feedback_feature: "Uusi ominaisuus"
    feedback_help: "Avunpyyntö"
    feedback_other: "Muu"
    feedback_message: "Viesti"
    feedback_button: "Lähetä palaute"
    about: "Tietoa palvelusta dbdesigner.net"
    user_settings: "Käyttäjäasetukset"
    user_settings_username: "Käyttäjänimi"
    user_settings_email: "Sähköposti"
    user_settings_save: "Tallenna muutokset"
    login: "Kirjaudu sisään"
    close: "Sulje"
    back: "Takaisin"
  designer:
    save_note_edit: "Tallenna"
    cancel_note_edit: "Peruuta"
    delete_note: "Poista"
    table_name: "Taulun nimi"
    table_comment: "Kommentti"
    table_save: "Tallenna"
    table_cancel: "Peruuta"
    table_delete: "Poista taulu"
    table_clone: "Luo taulusta kopio"
    table_add_field: "Lisää kenttä"
    field_name: "Nimi"
    field_type: "Tyyppi"
    field_size: "Koko"
    field_default: "Oletus"
    field_allow_nulls: "Salli null-arvot"
    field_primary_key: "Perusavain"
    field_foreign_key: "Viiteavain"
    field_save: "Tallenna"
    field_update: "Päivitä"
    field_cancel: "Peruuta"
    field_delete: "Poista kenttä"
    field_delete_alert: "Oletko varma että haluat poistaa tämän kentän?\n(pidä <shift> pohjassa poistaaksesi ilman varmistusta)"
    field_ref_table: "Viitattu taulu"
    field_ref_field: "Viitattu kenttä"
  alerts:
    delete_schema: "Oletko varma että haluat poistaa tämän kaavion?"
    server_error: "Virhe taustajärjestelmässä"
    schema_owner_error: "Ainoastaan kaavion omistaja voi muuttaa jakoasetuksia"
    login_to_use_this_function: "Kirjaudu sisään käyttääksesi tätä toimintoa"