I18n.kn =
  menu:
    schema: "ಸ್ಕೀಮಾ"
    new: "ಹೊಸ"
    load: "ಲೋಡ್"
    save: "ಉಳಿಸು"
    save_as: "ಉಳಿಸಿ"
    templates: "ಟೆಂಪ್ಲೇಟ್"
    properties: "ಗುಣಲಕ್ಷಣಗಳ"
    share: 
    import: 
    edit: 
    undo: 
    redo: 
    insert: 
    table: 
    note: 
    view: 
    show_minimap: 
    hide_minimap: 
    show_sidebar: 
    hide_sidebar: 
    show_grid: 
    hide_grid: 
    sort_items: 
    linetype: 
    bezier: 
    cornered: 
    options: 
    export: 
    sql: 
    image: 
    help: 
    index: 
    changes: 
    shortcuts: 
    feedback: 
    about: 
    guest: 
    login: 
    logout: 
    settings: 
  panel:
    history: 
    last_versions_label: 
    properties: 
    properties_schema_name: 
    properties_database: 
    comments: 
    comment_placeholder: 
    send: 
  dialog:
    new_schema: 
    new_schema_title: 
    new_schema_database: 
    new_schema_type_info: 
    new_schema_create_new: 
    load_schema: 
    load_schema_your_schemas: 
    load_schema_schema_name: 
    load_schema_database: 
    load_schema_last_save: 
    load_schema_shared_with_you: 
    load_schema_owner: 
    load_schema_no_schemas: 
    load_schema_no_shared_schemas: 
    saveas: 
    saveas_title: 
    saveas_button: 
    templates: 
    templates_schema_name: 
    templates_database: 
    templates_description: 
    properties: 
    properties_title: 
    properties_publish: 
    properties_template_info: 
    properties_delete_schema: 
    properties_delete_alert: 
    properties_save: 
    share: 
    share_info: 
    share_email: 
    share_access: 
    share_read_only: 
    share_read_write: 
    share_send_email: 
    share_invite_button: 
    share_collaborators: 
    import: 
    login_email: 
    login_password: 
    login_button: 
    login_forgot_password: 
    options: 
    options_line_colors: 
    options_invert_line_direction: 
    options_show_fk_icon: 
    options_show_not_null_icon: 
    options_show_default_values: 
    options_language: 
    options_save_changes: 
    export_sql: 
    export_sql_generate: 
    export_sql_download: 
    export_image: 
    export_image_zoomin: 
    export_image_zoomout: 
    export_image_reset: 
    export_image_open_in_new_tab: 
    help: 
    shortcuts: 
    help_changelog: 
    feedback: 
    feedback_type: 
    feedback_bug: 
    feedback_feature: 
    feedback_help: 
    feedback_other: 
    feedback_message: 
    feedback_button: 
    about: 
    user_settings: 
    user_settings_username: 
    user_settings_email: 
    user_settings_save: 
    login: 
    close: 
    back: 
  designer:
    save_note_edit: 
    cancel_note_edit: 
    delete_note: 
    table_name: 
    table_comment: 
    table_save: 
    table_cancel: 
    table_delete: 
    table_clone: 
    table_add_field: 
    field_name: 
    field_type: 
    field_size: 
    field_default: 
    field_allow_nulls: 
    field_primary_key: 
    field_foreign_key: 
    field_save: 
    field_update: 
    field_cancel: 
    field_delete: 
    field_delete_alert: 
    field_ref_table: 
    field_ref_field: 
  alerts:
    delete_schema: 
    server_error: 
    schema_owner_error: 
    login_to_use_this_function: 
