I18n.en =
  menu:
    schema: "Schema"
    new: "Nieuw ..."
    load: "Laden ..."
    save: "Opslaan"
    save_as: "Opslaan Als ..."
    templates: "Templates ..."
    properties: "Eigenschappen ..."
    share: "Delen ..."
    import: "Importeren ..."
    edit: "Bewerken"
    undo: "Ongedaan maken"
    redo: "Opnieuw uitvoeren"
    insert: "Invoegen"
    table: "Tabel"
    note: "Notitie"
    view: "Beeld"
    show_minimap: "Minimap Tonen"
    hide_minimap: "Minimap Verbergen"
    show_sidebar: "Zijbalk Tonen"
    hide_sidebar: "Zijbalk Verbergen"
    show_grid: "Raster Tonen"
    hide_grid: "Raster Verbergen"
    sort_items: "Items Sorteren"
    linetype: "Type Lijn"
    bezier: "Gebogen"
    cornered: "Hoekig"
    options: "Opties ..."
    export: "Exporteren"
    sql: "SQL ..."
    image: "Afbeelding ..."
    help: "Help"
    index: "Index"
    changes: "Wijzigingen"
    shortcuts: "Sneltoetsen"
    feedback: "Feedback geven"
    about: "Over"
    guest: "Gast"
    login: "Inloggen"
    logout: "Uitloggen"
    settings: "Instellingen"
  panel:
    history: "Geschiedenis"
    last_versions_label: "Laatste 10 versies van dit schema:"
    properties: "Eigenschappen"
    properties_schema_name: "Schema Naam:"
    properties_database: "Database:"
    comments: "Opmerkingen"
    comment_placeholder: "Plaats jouw opmerkingen hier"
    send: "Versturen"
  dialog:
    new_schema: "Nieuw Schema"
    new_schema_title: "Titel"
    new_schema_database: "Database"
    new_schema_type_info: """Door te kiezen voor het "generieke" datatypes type kan je SQL genereren voor alle databases; maar je hebt dan alleen toegang tot de generieke datatypen."""
    new_schema_create_new: "Nieuw Schema Maken"
    load_schema: "Schema Laden"
    load_schema_your_schemas: "Jouw Schemas:"
    load_schema_schema_name: "Schema Naam"
    load_schema_database: "Database"
    load_schema_last_save: "Opgeslagen Op"
    load_schema_shared_with_you: "Schemas die met jou gedeeld zijn:"
    load_schema_owner: "Eigenaar"
    load_schema_no_schemas: "Je hebt geen schemas opgeslagen"
    load_schema_no_shared_schemas: "Er zijn geen schemas met jou gedeeld"
    saveas: "Opslaan Als"
    saveas_title: "Titel"
    saveas_button: "Opslaan Als"
    templates: "Sjablonen"
    templates_schema_name: "Schema Naam"
    templates_database: "Database"
    templates_description: "Beschrijving"
    properties: "Schema Eigenschappen"
    properties_title: "Titel"
    properties_publish: "Publiceer als sjabloon"
    properties_template_info: "(Sjablonen zijn zichtbaar voor alle gebruikers)"
    properties_delete_schema: "Schema Verwijderen"
    properties_delete_alert: "(Hiermee verwijder je dit schema en alle geassocieerde opmerkingen)"
    properties_save: "Wijzigingen Opslaan"
    share: "Delen"
    share_info: "Je kan je schema met maximaal 5 gebruiker delen"
    share_email: "E-mail"
    share_access: "Toegang"
    share_read_only: "Alleen lezen"
    share_read_write: "Lezen en schrijven"
    share_send_email: "Verstuur uitnodiging via e-mail"
    share_invite_button: "Uitnodigen"
    share_collaborators: "Collaborators:"
    import: "SQL Importeren"
    login_email: "E-mail"
    login_password: "Wachtwoord"
    login_button: "Inloggen"
    login_forgot_password: "Ik ben mijn wachtwoord vergeten"
    options: "Opties"
    options_line_colors: "Line Colors"
    options_invert_line_direction: "Invert line direction"
    options_show_fk_icon: """"Foreign Key" Icoon Tonen"""
    options_show_not_null_icon: """"Not Null" Icoon Tonen"""
    options_show_default_values: "Standaardwaarden Tonen"
    options_language: "Taal"
    options_save_changes: "Wijzigingen Opslaan"
    export_sql: "SQL exporteren"
    export_sql_generate: "SQL henereren"
    export_sql_download: "SQL bestand Downloaden"
    export_image: "Afbeelding Exporteren"
    export_image_zoomin: "Inzoomen"
    export_image_zoomout: "Uitzoomen"
    export_image_reset: "Herstellen"
    export_image_open_in_new_tab: "Afbeelding in nieuw tabblad openen"
    help: "Help"
    shortcuts: "Sneltoetsen"
    help_changelog: "Wijzigingen"
    feedback: "Feedback"
    feedback_type: "Soort Feedback"
    feedback_bug: "Probleem rapportage"
    feedback_feature: "Functie voorstel"
    feedback_help: "Help"
    feedback_other: "Anders"
    feedback_message: "Bericht"
    feedback_button: "Feedback versturen"
    about: "Over dbdesigner.net"
    user_settings: "Gebruikers Instellingen"
    user_settings_username: "Gebruikersnaam"
    user_settings_email: "E-mail"
    user_settings_save: "Wijzigingen Opslaan"
    login: "Inloggen"
    close: "Sluiten"
    back: "Terug"
  designer:
    save_note_edit: "Opslaan"
    cancel_note_edit: "Annuleren"
    delete_note: "Verwijderen"
    table_name: "Tabel Naam"
    table_comment: "Tabel opmerking"
    table_save: "Opslaan"
    table_cancel: "Annuleren"
    table_delete: "Tabel Verwijderen"
    table_clone: "Tabel Dupliceren"
    table_add_field: "Veld toevoegen"
    field_name: "Naam"
    field_type: "Type"
    field_size: "Grootte"
    field_default: "Staandaardwaarde"
    field_allow_nulls: """"nulls" toestaan"""
    field_primary_key: "Primary Key"
    field_foreign_key: "Foreign Key"
    field_save: "Opslaan"
    field_update: "Bijwerken"
    field_cancel: "Annuleren"
    field_delete: "Veld verwijderen"
    field_delete_alert: "Weet je zeker dat je dit veld wilt verwijderen?\n(houd shift ingedrukt om te verwijderen zonder bevestiging)"
    field_ref_table: "Ref. Tabel"
    field_ref_field: "Ref. Veld"
  alerts:
    delete_schema: "Weet je zeker dat je dit schema wilt verwijderen?"
    server_error: "Er deed zich een probleem voor op de server"
    schema_owner_error: "Alleen de schema eigenaar kan de instellingen voor delen wijzigen"
    login_to_use_this_function: "Je moet inloggen om van deze functie gebruik te maken"
