I18n.pl =
  menu:
    schema: "Schemat"
    new: "Nowy ..."
    load: "Załaduj ..."
    save: "Zapisz"
    save_as: "Zapisz jako ..."
    templates: "Szablony ..."
    properties: "Właściwości ..."
    share: "Udostępnij ..."
    import: "Import ..."
    edit: "Edytuj"
    undo: "Zafnij"
    redo: "Powtórz"
    insert: "Wstaw"
    table: "Tabela"
    note: "Notatka"
    view: "Widok"
    show_minimap: "Pokaż Minimape"
    hide_minimap: "Schowaj Minimape"
    show_sidebar: "Pokaż Sidebar"
    hide_sidebar: "Schowaj Sidebar"
    show_grid: "Pokaż Siatkę"
    hide_grid: "Schowaj Siatkę"
    sort_items: "Sort Items"
    linetype: "Rodzaj linii"
    bezier: "Bezier"
    cornered: "Cornered"
    options: "Opcje ..."
    export: "Export"
    sql: "Sql ..."
    image: "Obraz ..."
    help: "Pomoc"
    index: "Index"
    changes: "Zmiany"
    shortcuts: "Skróty klawiszowe"
    feedback: "Zgłoś błąd"
    about: "O nas"
    guest: "Gość"
    login: "Login"
    logout: "Wyloguj"
    settings: "Ustawienia"
  panel:
    history: "Historia"
    last_versions_label: "Ostatnie 10 wersji schematu:"
    properties: "Właściwości"
    properties_schema_name: "Nazwa Schematu:"
    properties_database: "Baza danych:"
    comments: "Komentarze"
    comment_placeholder: "Wpisz swój komentarz tutaj"
    send: "Wyślij"
  dialog:
    new_schema: "Nowy schemat"
    new_schema_title: "Tytuł"
    new_schema_database: "Baza danych"
    new_schema_type_info: """Wybór "ogólny" typu bazy danychpozwala na generowanie SQL dla wszystkich baz danych; Ale będziesz miał dostęp do tylko podstawowych typów danych."""
    new_schema_create_new: "Stwórz nowy schemat"
    load_schema: "Wczytaj Schemat"
    load_schema_your_schemas: "Twoje Schematy:"
    load_schema_schema_name: "Nazwy Schematów"
    load_schema_database: "Baza Danych"
    load_schema_last_save: "Ostatni zapis"
    load_schema_shared_with_you: "Schematy udostępnione przez Ciebie:"
    load_schema_owner: "Właściciel"
    load_schema_no_schemas: "Nie zapisałś żadnych schematów"
    load_schema_no_shared_schemas: "Nie ma żadnych schematów udostępnionych przez Ciebie"
    saveas: "Zapisz jako"
    saveas_title: "Tytuł"
    saveas_button: "Zapisz jako"
    templates: "Szablony"
    templates_schema_name: "Nazwa Schematu"
    templates_database: "Baza Danych"
    templates_description: "opis"
    properties: "Właściwości Schematu"
    properties_title: "Tytuł"
    properties_publish: "Publish as template"
    properties_template_info: "(Templates are visible to every user)"
    properties_delete_schema: "Delete Schema"
    properties_delete_alert: "(You will permanently delete this schema and all associated comments)"
    properties_save: "Save Changes"
    share: "Share"
    share_info: "You can share your schema with up to 5 users"
    share_email: "E-mail"
    share_access: "Access"
    share_read_only: "Read only"
    share_read_write: "Read and write"
    share_send_email: "Send invitation e-mail"
    share_invite_button: "Invite"
    share_collaborators: "Collaborators:"
    import: "Import Sql"
    login_email: "E-mail"
    login_password: "Password"
    login_button: "Login"
    login_forgot_password: "I forgot my password"
    options: "Options"
    options_line_colors: "Line Colors"
    options_invert_line_direction: "Invert line direction"
    options_show_fk_icon: "Show Foreign Key Icon"
    options_show_not_null_icon: "Show Not Null icon"
    options_show_default_values: "Show Default Values"
    options_language: "Language"
    options_save_changes: "Save Changes"
    export_sql: "Export SQL"
    export_sql_generate: "Generate SQL"
    export_sql_download: "Download SQL file"
    export_image: "Export Image"
    export_image_zoomin: "Zoom in"
    export_image_zoomout: "Zoom out"
    export_image_reset: "Reset"
    export_image_open_in_new_tab: "Open image in new tab"
    help: "Pomoc"
    shortcuts: "Skróty Klawiszowe"
    help_changelog: "Zmiany"
    feedback: "Powiadomienie"
    feedback_type: "Typ Powiadomienia"
    feedback_bug: "Report Bugów"
    feedback_feature: "Zgłoszanie Pomysłów"
    feedback_help: "Pomoc"
    feedback_other: "Inne"
    feedback_message: "Wiadomość"
    feedback_button: "Wyślij powiadomienie"
    about: "O dbdesigner.net"
    user_settings: "Ustawienia Użytkownika"
    user_settings_username: "Nazwa Użytkownika"
    user_settings_email: "E-mail"
    user_settings_save: "Zapisz Zmiany"
    login: "Login"
    close: "Zamknij"
    back: "Cofnij"
  designer:
    save_note_edit: "Zapisz"
    cancel_note_edit: "Anuluj"
    delete_note: "Usuń"
    table_name: "Nazwa Tabeli"
    table_comment: "Komentarz Tabeli"
    table_save: "Zapisz"
    table_cancel: "Anuluj"
    table_delete: "Usuń Tabele"
    table_clone: "Zklonuj Tabele"
    table_add_field: "Dodaj Pole"
    field_name: "Nazwa"
    field_type: "Typ"
    field_size: "Rozmiar"
    field_default: "Domyślna"
    field_allow_nulls: "Zezwalaj na wartości null"
    field_primary_key: "Primary Key"
    field_foreign_key: "Foreign Key"
    field_save: "Zapisz"
    field_update: "Update"
    field_cancel: "Anuluj"
    field_delete: "Usuń Pole"
    field_delete_alert: "Jesteś pewien, że chcesz usunąć to pole?\n(przytrzymaj shift, aby usuwać bez powiadomienia)"
    field_ref_table: "Odśwież Tabele"
    field_ref_field: "Odśwież Pole"
  alerts:
    delete_schema: "Jesteś pewien, że chcesz usunąć ten schemat?"
    server_error: "Wystąpił błąd serwera"
    schema_owner_error: "Tylko właściciel może zmienić ustawienia schematu"
    login_to_use_this_function: "Zaloguj się, aby skorzystać z tej funkcji"