I18n.pt_br =
  menu:
    schema: "Esquema"
    new: "Novo ..."
    load: "Carregar ..."
    save: "Salvar"
    save_as: "Salvar como ..."
    templates: "Modelos ..."
    properties: "Propriedades ..."
    share: "Compartilhar ..."
    import: "Importar ..."
    edit: "Editar"
    undo: "Desfazer"
    redo: "Refazer"
    insert: "Inserir"
    table: "Tabela"
    note: "Anotação"
    view: "Exibir"
    show_minimap: "Mostrar Minimapa"
    hide_minimap: "Esconder Minimapa"
    show_sidebar: "Mostrar Barra Lateral"
    hide_sidebar: "Esconder Barra Lateral"
    show_grid: "Mostrar Grade"
    hide_grid: "Esconder Grade"
    sort_items: "Ordenar Itens"
    linetype: "Tipo de Linha"
    bezier: "Curva"
    cornered: "Reta"
    options: "Opções ..."
    export: "Exportar"
    sql: "SQL ..."
    image: "Imagem ..."
    help: "Ajuda"
    index: "Índice"
    changes: "Alterações"
    shortcuts: "Atalhos do Teclado"
    feedback: "Feedback"
    about: "Sobre"
    guest: "Convidado"
    login: "Login"
    logout: "Logout"
    settings: "Configurações"
  panel:
    history: "Histórico"
    last_versions_label: "Últimas 10 versões deste esquema:"
    properties: "Propriedades"
    properties_schema_name: "Nome do Esquema:"
    properties_database: "Banco de Dados:"
    comments: "Comentários"
    comment_placeholder: "Digite o seu comentário aqui"
    send: "Enviar"
  dialog:
    new_schema: "Novo esquema"
    new_schema_title: "Título"
    new_schema_database: "Banco de Dados"
    new_schema_type_info: """Selecionando o tipo de banco de dados "genérico" permitirá gerar SQL para todos os bancos de dados; porém você só terá acesso a tipos de dados genéricos."""
    new_schema_create_new: "Criar Novo Esquema"
    load_schema: "Carregar Esquema"
    load_schema_your_schemas: "Seus Esquemas:"
    load_schema_schema_name: "Nome do Esquema"
    load_schema_database: "Banco de Dados"
    load_schema_last_save: "Último salvo"
    load_schema_shared_with_you: "Esquemas compartilhados com você:"
    load_schema_owner: "Proprietário"
    load_schema_no_schemas: "Você não salvou nenhum esquema"
    load_schema_no_shared_schemas: "Não há esquemas compartilhados com você"
    saveas: "Salvar Como"
    saveas_title: "Título"
    saveas_button: "Salvar Como"
    templates: "Modelos"
    templates_schema_name: "Nome do Esquema"
    templates_database: "Banco de Dados"
    templates_description: "Descrição"
    properties: "Propriedades de Esquema"
    properties_title: "Título"
    properties_publish: "Publicar como modelo"
    properties_template_info: "(Os modelos são visíveis para todos os usuários)"
    properties_delete_schema: "Excluir Esquema"
    properties_delete_alert: "(Você vai apagar permanentemente este esquema e todos os comentários associados)"
    properties_save: "Salvar Alterações"
    share: "Compartilhar"
    share_info: "Você pode compartilhar seu esquema com até 5 usuários"
    share_email: "E-mail"
    share_access: "Acesso"
    share_read_only: "Somente Leitura"
    share_read_write: "Leitura e Escrita"
    share_send_email: "Enviar convite por e-mail"
    share_invite_button: "Convidar"
    share_collaborators: "Colaboradores:"
    import: "Importar SQL"
    login_email: "E-mail"
    login_password: "Senha"
    login_button: "Login"
    login_forgot_password: "Esqueci minha senha"
    options: "Opções"
    options_line_colors: "Cor das Linhas"
    options_invert_line_direction: "Inverter Direção das Linhas"
    options_show_fk_icon: "Mostrar Ícones de Chave Estrangeira"
    options_show_not_null_icon: "Mostrar Ícones de Não-Nulo"
    options_show_default_values: "Mostrar Valores Padrões"
    options_language: "Idioma"
    options_save_changes: "Salvar Alterações"
    export_sql: "Exportar SQL"
    export_sql_generate: "Gerar SQL"
    export_sql_download: "Baixar arquivo SQL"
    export_image: "Exportar Imagem"
    export_image_zoomin: "Ampliar"
    export_image_zoomout: "Diminuir"
    export_image_reset: "Reiniciar"
    export_image_open_in_new_tab: "Abrir imagem numa nova aba"
    help: "Ajuda"
    shortcuts: "Atalhos do Teclado"
    help_changelog: "Alterações"
    feedback: "Feedback"
    feedback_type: "Tipo de Feedback"
    feedback_bug: "Relatar Erro"
    feedback_feature: "Sugerir Modificação"
    feedback_help: "Ajuda"
    feedback_other: "Outros"
    feedback_message: "Mensagem"
    feedback_button: "Enviar Feedback"
    about: "Sobre dbdesigner.net"
    user_settings: "Configurações do Usuário"
    user_settings_username: "Nome de Usuário"
    user_settings_email: "E-mail"
    user_settings_save: "Salvar Alterações"
    login: "Login"
    close: "Fechar"
    back: "Voltar"
  designer:
    save_note_edit: "Salvar"
    cancel_note_edit: "Cancelar"
    delete_note: "Delete"
    table_name: "Nome da Tabela"
    table_comment: "Comentário da Tabela"
    table_save: "Salvar"
    table_cancel: "Cancelar"
    table_delete: "Excluir Tabela"
    table_clone: "Clonar Tabela"
    table_add_field: "Adicionar campo"
    field_name: "Nome"
    field_type: "Tipo"
    field_size: "Tamanho"
    field_default: "Valor Padrão"
    field_allow_nulls: "Permitir valores nulos"
    field_primary_key: "Chave Primária"
    field_foreign_key: "Chave Estrangeira"
    field_save: "Salvar"
    field_update: "Atualizar"
    field_cancel: "Cancelar"
    field_delete: "Excluír Campo"
    field_delete_alert: "Tem certeza de que deseja excluir este campo?\n(segure o Shift para excluir sem confirmação)"
    field_ref_table: "Tabela de Referência"
    field_ref_field: "Campo de Referência"
  alerts:
    delete_schema: "Tem certeza de que deseja excluir este esquema?"
    server_error: "Ocorreu um erro no servidor"
    schema_owner_error: "Apenas o proprietário do esquema pode alterar as configurações de compartilhamento"
    login_to_use_this_function: "Você deve efetuar o login para utilizar esta função"
